apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-template-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs-template
  template:
    metadata:
      labels:
        app: nestjs-template
    spec:
      containers:
        - name: nestjs-template
          image: danielwj00/nestjs_template
          ports:
            - containerPort: 3300
          env:
            - name: MYSQL_DB_HOST
              value: host.docker.internal
            - name: PG_DB_HOST
              value: host.docker.internal
          imagePullPolicy: IfNotPresent
