apiVersion: v1
kind: Service
metadata:
  name: nestjs-template
spec:
  selector:
    app: nestjs-template
  ports:
    - protocol: TCP
      port: 3300
      targetPort: 3300
      nodePort: 31000
  type: LoadBalancer
